In [10]:
import torch
train_rand = torch.randn(4, 2, dtype=torch.float64)
test_rand = torch.randn(2, 4, dtype=torch.float64)

In [11]:
train_rand

tensor([[-0.9831, -0.3472],
        [ 0.2231, -0.7634],
        [-1.2450, -1.1245],
        [ 0.1519,  2.6790]], dtype=torch.float64)

In [12]:
test_rand

tensor([[-1.0576,  2.2043, -1.7842, -0.4190],
        [-1.2732, -0.9101, -0.1591, -2.1856]], dtype=torch.float64)

In [14]:
torch.mm(train_rand, test_rand)

tensor([[ 1.4819, -1.8511,  1.8094,  1.1708],
        [ 0.7360,  1.1866, -0.2766,  1.5751],
        [ 2.7485, -1.7209,  2.4003,  2.9793],
        [-3.5715, -2.1034, -0.6973, -5.9188]], dtype=torch.float64)